DROP DATABASE IF EXISTS adweb;

CREATE DATABASE adweb CHARACTER SET UTF8;

CREATE TABLE adweb.user(
  uid INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(20),
  password VARCHAR(20),
  portrait VARCHAR(20)
)CHARACTER SET UTF8;